import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
const root=dirname(dirname(fileURLToPath(import.meta.url)));
test('help exposes Kodematik v0.6.16 instruction delivery integrity',()=>{
  const out=execFileSync(process.execPath,[join(root,'src','cli.js'),'help'],{encoding:'utf8'});
  assert.match(out,/Kodematik v0\.6\.16/);
  assert.match(out,/kodematik qualify/);
  assert.match(out,/kodematik baseline/);
  assert.match(out,/kodematik evolve/);
  assert.match(out,/--agent codex\|openrouter/);
  assert.match(out,/deepseek\/deepseek-v4-flash/);
  assert.match(out,/--tasks N/);
  assert.match(out,/--scan-limit N/);
  assert.match(out,/--expected-fingerprint SHA256/);
  assert.match(out,/--qualification-budget-min N/);
  assert.match(out,/--verification-timeout-sec N/);
  assert.match(out,/--install-timeout-sec N/);
  assert.match(out,/--holdout PERCENT/);
  assert.match(out,/--candidates N/);
  assert.match(out,/--trials N/);
  assert.match(out,/--max-turns N/);
  assert.match(out,/Instruction Delivery Integrity/);
  assert.match(out,/AGENTS\.md into the actual system context/);
  assert.match(out,/fingerprints the exact delivered instructions/);
  assert.match(out,/task-specific and frozen/);
  assert.match(out,/majority training wins/);
  assert.match(out,/zero held-out regressions/);
  assert.match(out,/Fingerprint-locked qualification/);
  assert.match(out,/instruction-delivery evidence/);
  assert.match(out,/--install/);
});
